# Generated by Django 4.2.1 on 2023-05-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
