# Generated by Django 4.2.1 on 2023-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_vocabulary_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="number_user_learned",
            field=models.IntegerField(default=0),
        ),
    ]
