# Generated by Django 4.2.1 on 2023-07-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_course_number_user_learned"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="delete_flag",
            field=models.BooleanField(default=False),
        ),
    ]
