# Generated by Django 4.2.1 on 2023-06-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingcourse",
            name="comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="ratinggroup",
            name="comment",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
