# Generated by Django 4.2.1 on 2023-06-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="user_invite_join",
            field=models.IntegerField(),
        ),
    ]
