# Generated by Django 4.2.1 on 2023-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("group", "0002_alter_groupmember_user_invite_join"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private")],
                default="public",
                max_length=20,
            ),
        ),
    ]
